/**
 * Redes Integradas de Telecomunicações I
 * MIEEC 2015/2016
 *
 * router.java
 *
 * Main class and graphic interface class with auxiliar functions
 *
 * @author  Luis Bernardo
 */
package router;

import java.net.*;
import java.io.*;


public class router extends javax.swing.JFrame {
    
    public final static byte PKT_HELLO = 21;
    public final static byte PKT_BYE = 22;
    public final static byte PKT_ROUTE = 10;
    public final static byte PKT_DATA = 109;
    public final static int MAX_DISTANCE = 50;
    public final static int MAX_PATH_LEN = 8;
    
    /** Creates new form router */
    public router() {
        // Start main window
        initComponents();
        // Start neighbour list
        neig= new neighbourList(tabelaViz.getRowCount(), this);
        
        ds= null;
        daemon= null;
        route= null;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        editName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        editIP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        editPorto = new javax.swing.JTextField();
        tbuttonActive = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaViz = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        buttonAdd = new javax.swing.JButton();
        buttonRem = new javax.swing.JButton();
        buttonDist = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        editNeigName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        editNeigDist = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        editNeigIP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        editNeigPorto = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        checkSndIfChanges = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        editPeriodo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        editMinInterval = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jCheckBoxMulticast = new javax.swing.JCheckBox();
        editIPMulticast = new javax.swing.JTextField();
        editPortMulticast = new javax.swing.JTextField();
        checkSlowData = new javax.swing.JCheckBox();
        editDataDelay = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaRoute = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        buttonEnviar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        editNomeDest = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        editMensagem = new javax.swing.JTextField();
        buttonLimpar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();

        setTitle("T1 RIT1 40581-40753-40895       2015/2016");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(345, 35));
        jPanel1.setMinimumSize(new java.awt.Dimension(320, 35));
        jPanel1.setPreferredSize(new java.awt.Dimension(345, 35));

        jLabel1.setText("Name");
        jPanel1.add(jLabel1);

        editName.setText("A");
        editName.setMaximumSize(new java.awt.Dimension(20, 19));
        editName.setMinimumSize(new java.awt.Dimension(18, 19));
        editName.setPreferredSize(new java.awt.Dimension(20, 19));
        jPanel1.add(editName);

        jLabel2.setText("IP");
        jPanel1.add(jLabel2);

        editIP.setText("127.0.0.1");
        editIP.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel1.add(editIP);

        jLabel3.setText("Port");
        jLabel3.setMaximumSize(new java.awt.Dimension(33, 17));
        jLabel3.setPreferredSize(new java.awt.Dimension(33, 17));
        jPanel1.add(jLabel3);

        editPorto.setText("20000");
        editPorto.setMaximumSize(new java.awt.Dimension(49, 20));
        editPorto.setMinimumSize(new java.awt.Dimension(45, 20));
        editPorto.setPreferredSize(new java.awt.Dimension(49, 20));
        jPanel1.add(editPorto);

        tbuttonActive.setText("Active");
        tbuttonActive.setMargin(new java.awt.Insets(1, 2, 1, 2));
        tbuttonActive.setPreferredSize(new java.awt.Dimension(73, 25));
        tbuttonActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbuttonActiveActionPerformed(evt);
            }
        });
        jPanel1.add(tbuttonActive);

        getContentPane().add(jPanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(320, 140));
        jPanel2.setMinimumSize(new java.awt.Dimension(320, 75));
        jPanel2.setPreferredSize(new java.awt.Dimension(320, 75));
        jPanel2.setLayout(null);

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(300, 140));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(300, 70));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 70));

        tabelaViz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "IP", "Port", "Distance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaViz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVizMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaViz);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 5, 300, 70);

        getContentPane().add(jPanel2);

        jPanel3.setMaximumSize(new java.awt.Dimension(320, 35));
        jPanel3.setMinimumSize(new java.awt.Dimension(320, 35));
        jPanel3.setPreferredSize(new java.awt.Dimension(320, 35));

        buttonAdd.setText("Add Neig");
        buttonAdd.setMargin(new java.awt.Insets(2, 2, 2, 2));
        buttonAdd.setMaximumSize(new java.awt.Dimension(90, 26));
        buttonAdd.setMinimumSize(new java.awt.Dimension(80, 25));
        buttonAdd.setPreferredSize(new java.awt.Dimension(90, 25));
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });
        jPanel3.add(buttonAdd);

        buttonRem.setText("Rem. Neig");
        buttonRem.setMargin(new java.awt.Insets(2, 2, 2, 2));
        buttonRem.setMaximumSize(new java.awt.Dimension(90, 26));
        buttonRem.setMinimumSize(new java.awt.Dimension(90, 25));
        buttonRem.setPreferredSize(new java.awt.Dimension(90, 26));
        buttonRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemActionPerformed(evt);
            }
        });
        jPanel3.add(buttonRem);

        buttonDist.setText("Mod. Neig");
        buttonDist.setMargin(new java.awt.Insets(2, 2, 2, 2));
        buttonDist.setMaximumSize(new java.awt.Dimension(90, 26));
        buttonDist.setMinimumSize(new java.awt.Dimension(80, 25));
        buttonDist.setPreferredSize(new java.awt.Dimension(90, 26));
        buttonDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDistActionPerformed(evt);
            }
        });
        jPanel3.add(buttonDist);

        getContentPane().add(jPanel3);

        jPanel8.setMaximumSize(new java.awt.Dimension(340, 30));

        jLabel11.setText(" Name");
        jPanel8.add(jLabel11);

        editNeigName.setText("B");
        editNeigName.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel8.add(editNeigName);

        jLabel10.setText(" Dist.");
        jPanel8.add(jLabel10);

        editNeigDist.setText("1");
        editNeigDist.setMinimumSize(new java.awt.Dimension(20, 20));
        editNeigDist.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel8.add(editNeigDist);

        jLabel8.setText("IP");
        jPanel8.add(jLabel8);

        editNeigIP.setText("127.1.1.1");
        editNeigIP.setMaximumSize(new java.awt.Dimension(200, 20));
        editNeigIP.setMinimumSize(new java.awt.Dimension(80, 20));
        editNeigIP.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel8.add(editNeigIP);

        jLabel9.setText("Port");
        jLabel9.setMaximumSize(new java.awt.Dimension(33, 17));
        jLabel9.setPreferredSize(new java.awt.Dimension(33, 17));
        jPanel8.add(jLabel9);

        editNeigPorto.setText("20000");
        editNeigPorto.setMinimumSize(new java.awt.Dimension(45, 20));
        editNeigPorto.setPreferredSize(new java.awt.Dimension(49, 20));
        jPanel8.add(editNeigPorto);

        getContentPane().add(jPanel8);

        jPanel7.setMaximumSize(new java.awt.Dimension(338, 30));
        jPanel7.setMinimumSize(new java.awt.Dimension(307, 30));
        jPanel7.setPreferredSize(new java.awt.Dimension(338, 30));

        checkSndIfChanges.setText("Send if changes");
        checkSndIfChanges.setMaximumSize(new java.awt.Dimension(145, 23));
        checkSndIfChanges.setMinimumSize(new java.awt.Dimension(130, 23));
        checkSndIfChanges.setPreferredSize(new java.awt.Dimension(145, 23));
        checkSndIfChanges.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkSndIfChangesItemStateChanged(evt);
            }
        });
        jPanel7.add(checkSndIfChanges);

        jLabel6.setText("Period");
        jPanel7.add(jLabel6);

        editPeriodo.setText("10");
        editPeriodo.setPreferredSize(new java.awt.Dimension(25, 19));
        jPanel7.add(editPeriodo);

        jLabel7.setText("Min Interval");
        jPanel7.add(jLabel7);

        editMinInterval.setText("0");
        editMinInterval.setMaximumSize(new java.awt.Dimension(20, 19));
        editMinInterval.setMinimumSize(new java.awt.Dimension(20, 19));
        editMinInterval.setPreferredSize(new java.awt.Dimension(20, 19));
        jPanel7.add(editMinInterval);

        getContentPane().add(jPanel7);

        jPanel9.setMaximumSize(new java.awt.Dimension(330, 32));
        jPanel9.setMinimumSize(new java.awt.Dimension(330, 30));
        jPanel9.setPreferredSize(new java.awt.Dimension(330, 32));

        jCheckBoxMulticast.setSelected(true);
        jCheckBoxMulticast.setText("Mult");
        jCheckBoxMulticast.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxMulticast.setMaximumSize(new java.awt.Dimension(54, 18));
        jCheckBoxMulticast.setPreferredSize(new java.awt.Dimension(51, 18));
        jCheckBoxMulticast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMulticastActionPerformed(evt);
            }
        });
        jPanel9.add(jCheckBoxMulticast);

        editIPMulticast.setText("225.0.0.1");
        editIPMulticast.setMaximumSize(new java.awt.Dimension(70, 19));
        editIPMulticast.setMinimumSize(new java.awt.Dimension(65, 19));
        editIPMulticast.setPreferredSize(new java.awt.Dimension(70, 19));
        jPanel9.add(editIPMulticast);

        editPortMulticast.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        editPortMulticast.setText("19000");
        editPortMulticast.setMaximumSize(new java.awt.Dimension(36, 19));
        editPortMulticast.setMinimumSize(new java.awt.Dimension(36, 19));
        jPanel9.add(editPortMulticast);

        checkSlowData.setText("Slow data");
        checkSlowData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSlowDataActionPerformed(evt);
            }
        });
        jPanel9.add(checkSlowData);

        editDataDelay.setText("500");
        editDataDelay.setMaximumSize(new java.awt.Dimension(40, 19));
        editDataDelay.setMinimumSize(new java.awt.Dimension(20, 19));
        editDataDelay.setPreferredSize(new java.awt.Dimension(40, 27));
        editDataDelay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDataDelayActionPerformed(evt);
            }
        });
        jPanel9.add(editDataDelay);

        getContentPane().add(jPanel9);

        jPanel4.setMaximumSize(new java.awt.Dimension(320, 200));
        jPanel4.setMinimumSize(new java.awt.Dimension(320, 120));
        jPanel4.setPreferredSize(new java.awt.Dimension(320, 120));
        jPanel4.setLayout(null);

        jScrollPane2.setMaximumSize(new java.awt.Dimension(300, 400));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(300, 115));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(300, 115));
        jScrollPane2.setAutoscrolls(true);

        tabelaRoute.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Destination", "Router", "Distance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaRoute.setMaximumSize(new java.awt.Dimension(300, 500));
        tabelaRoute.setMinimumSize(new java.awt.Dimension(300, 400));
        tabelaRoute.setPreferredScrollableViewportSize(new java.awt.Dimension(300, 500));
        tabelaRoute.setPreferredSize(new java.awt.Dimension(300, 400));
        jScrollPane2.setViewportView(tabelaRoute);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(10, 5, 300, 115);

        getContentPane().add(jPanel4);

        jPanel5.setMaximumSize(new java.awt.Dimension(330, 39));
        jPanel5.setMinimumSize(new java.awt.Dimension(320, 35));
        jPanel5.setPreferredSize(new java.awt.Dimension(330, 39));

        buttonEnviar.setText("Send");
        buttonEnviar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        buttonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSendActionPerformed(evt);
            }
        });
        jPanel5.add(buttonEnviar);

        jLabel4.setText("Dest:");
        jPanel5.add(jLabel4);

        editNomeDest.setText("A");
        editNomeDest.setMaximumSize(new java.awt.Dimension(20, 20));
        editNomeDest.setMinimumSize(new java.awt.Dimension(16, 20));
        editNomeDest.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel5.add(editNomeDest);

        jLabel5.setText("Msg:");
        jPanel5.add(jLabel5);

        editMensagem.setText("test 1");
        editMensagem.setMaximumSize(new java.awt.Dimension(90, 19));
        editMensagem.setMinimumSize(new java.awt.Dimension(90, 19));
        editMensagem.setPreferredSize(new java.awt.Dimension(90, 19));
        jPanel5.add(editMensagem);

        buttonLimpar.setText("Clear");
        buttonLimpar.setMargin(new java.awt.Insets(2, 5, 2, 5));
        buttonLimpar.setMaximumSize(new java.awt.Dimension(59, 33));
        buttonLimpar.setPreferredSize(new java.awt.Dimension(59, 33));
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });
        jPanel5.add(buttonLimpar);

        getContentPane().add(jPanel5);

        jPanel6.setMaximumSize(new java.awt.Dimension(320, 180));
        jPanel6.setMinimumSize(new java.awt.Dimension(320, 100));
        jPanel6.setPreferredSize(new java.awt.Dimension(320, 180));
        jPanel6.setLayout(null);

        jScrollPane3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jScrollPane3.setMaximumSize(new java.awt.Dimension(301, 175));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(301, 100));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(301, 175));
        jScrollPane3.setAutoscrolls(true);

        texto.setColumns(20);
        texto.setEditable(false);
        texto.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        texto.setMaximumSize(new java.awt.Dimension(180, 800));
        texto.setMinimumSize(new java.awt.Dimension(180, 100));
        texto.setPreferredSize(new java.awt.Dimension(180, 800));
        texto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(texto);

        jPanel6.add(jScrollPane3);
        jScrollPane3.setBounds(9, 5, 301, 175);

        getContentPane().add(jPanel6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoKeyPressed
        // Add your handling code here:
        if (evt.getKeyChar() == 's')
            write_statistics();
        if (evt.getKeyChar() == 'z')
            zero_statistics();
    }//GEN-LAST:event_textoKeyPressed

    private void checkSndIfChangesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkSndIfChangesItemStateChanged
    }//GEN-LAST:event_checkSndIfChangesItemStateChanged

    // Returns true if "Multicast" is selected
    public boolean is_multicast() {
        return jCheckBoxMulticast.isSelected();
    }

    // Returns true if "SendIfChanges" is selected
    public boolean is_SendIfChanges() {
        return checkSndIfChanges.isSelected();
    }

    // Returns true if "slowdata" is selected
    public boolean is_SlowData() {
        return checkSlowData.isSelected();
    }

    /** Updates edit windows with selected line data */
    private void tabelaVizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVizMouseClicked
        int row= tabelaViz.getSelectedRow();
        if (row == -1) { // Line not selected
            return;
        }
        for (int i= 0; i<4; i++) {
            String s= (String)tabelaViz.getValueAt(row, i);
            if (s == null)
                return;
            switch (i) {
                case 0: editNeigName.setText(s); break;
                case 1: editNeigIP.setText(s); break;
                case 2: editNeigPorto.setText(s); break;
                case 3: editNeigDist.setText(s); break;
            }
        }
    }//GEN-LAST:event_tabelaVizMouseClicked

    /* Cleans texto contents */
    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        texto.setText("");
    }//GEN-LAST:event_buttonClearActionPerformed

    /* Sends test packet */
    private void buttonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSendActionPerformed
        if (!tbuttonActive.isSelected()) {
            Log("Router is not active\n");
            return;
        }
        synchronized (main_lock) {
            route.send_new_data_packet(local_name(),
                editNomeDest.getText().charAt(0), editMensagem.getText(), "");
        }
    }//GEN-LAST:event_buttonSendActionPerformed

    /** Changes distance to neighbour */
    private void buttonDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDistActionPerformed
        if (!tbuttonActive.isSelected()) {
            Log("Router is not active\n");
            return;
        }
        if (neig.locate_neig(editNeigName.getText().charAt(0)) == null) {
            Log("Invalid neighbour\n");
            return;
        }
        try {
            synchronized (main_lock) {
                if (neig.update_neig(editNeigName.getText().charAt(0), 
                              editNeigIP.getText(), 
                              Integer.parseInt(editNeigPorto.getText()),
                              Integer.parseInt(editNeigDist.getText()))) { /***************/
                    neig.refresh_table(tabelaViz);
                    if (checkSndIfChanges.isSelected()) {
                        route.network_changed(true);
                    }
                }
            }
        }
        catch (NumberFormatException e) { 
            Log("Invalid number\n");
        }
    }//GEN-LAST:event_buttonDistActionPerformed

    /** Removes neighour from list */
    private void buttonRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemActionPerformed
        if (!tbuttonActive.isSelected()) {
            Log("Router is not active\n");
            return;
        }
        if (neig.locate_neig(editNeigName.getText().charAt(0)) == null) {
            Log("Invalid neighbour\n");
            return;
        }
        synchronized (main_lock) {
            if (neig.del_neig(editNeigName.getText().charAt(0), true, ds, 
                          local_name())) {
                neig.refresh_table(tabelaViz);
                if (checkSndIfChanges.isSelected()) {
                    route.network_changed(true);
                }
            }
        }
    }//GEN-LAST:event_buttonRemActionPerformed

    /** Adds new neighbour to the list */
    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        if (!tbuttonActive.isSelected()) {
            Log("Router is not active\n");
            return;
        }
        String new_name= editNeigName.getText();
        if (new_name.length()>1 || !Character.isUpperCase(new_name.charAt(0))) {
            Log("Invalid name '"+new_name+"'\n");
            return;
        }
        if (neig.locate_neig(new_name.charAt(0)) != null) {
            Log("Duplicate name\n");
            return;            
        }
        synchronized (main_lock) {
            try {
                if (neig.add_neig(new_name.charAt(0), 
                              editNeigIP.getText(), 
                              Integer.parseInt(editNeigPorto.getText()),
                              Integer.parseInt(editNeigDist.getText()),
                              ds)) {
                    neig.refresh_table(tabelaViz);
                    if (checkSndIfChanges.isSelected()) {
                        route.network_changed(true);
                    }
                }
            }
            catch (NumberFormatException e) { 
                Log("Invalid number\n");
            }
        }
    }//GEN-LAST:event_buttonAddActionPerformed

    /** Activates or stops the router */
    private void tbuttonActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbuttonActiveActionPerformed
        if (tbuttonActive.isSelected()) {
            // Start router
            boolean activo= false;
            try {
                int port= Integer.parseInt(editPorto.getText());
                char c= editName.getText().charAt(0);              
                int period= Integer.parseInt(editPeriodo.getText());
                int minInterval= Integer.parseInt(editMinInterval.getText());
                int mport= Integer.parseInt (editPortMulticast.getText());
                int data_delay= Integer.parseInt (editDataDelay.getText());
                do {
                    try {
                        ds= new DatagramSocket(port);
                        activo= true;
                    }
                    catch (SocketException se) {
                        // Skip to next letter
                        port++;
                        c++;
                    }
                } while (!activo && (c<='Z'));
                
                if (!activo) {
                    Log("All letters ('A'-'Z') occupied\n");
                    tbuttonActive.setSelected(false);
                    return;
                }
                 // Update edit boxes
                editPorto.setText(""+port);
                editName.setText(""+c);
                editIP.setText(InetAddress.getLocalHost().getHostAddress());
                editNomeDest.setText (""+c);
                if (c<'Z') c++; else c--;
                editNeigName.setText(""+c);
                editNeigPorto.setText(""+(port+1));
                editNeigIP.setText(InetAddress.getLocalHost().getHostAddress());

                // Start routing timer
                route= new routing(local_name(), neig, 
                    period, minInterval, data_delay,
                    editIPMulticast.getText(), mport, this, ds, tabelaRoute);
                if (!route.start()) {
                    Log("Failed to boot the routing object\n");
                    ds.close();
                    ds= null;
                    tbuttonActive.setSelected(false);
                    return;
                }
                // Start daemon thread
                daemon= new Daemon(ds);
                daemon.start();
                // Lock entry windows
                editName.setEditable(false);                
                editPorto.setEditable(false);
                editIP.setEditable(false);
//                checkSndIfChanges.setEnabled(false);
                editPeriodo.setEditable(false);
                editMinInterval.setEditable(false);
//                jCheckBoxMulticast.setEnabled(false);
                editPortMulticast.setEditable(false);
                editIPMulticast.setEditable(false);
//                checkSlowData.setEnabled(false);
                editDataDelay.setEditable(false);
                //
                zero_statistics();
            }
            catch (UnknownHostException e) {
                Log("Localhost Unknown: "+e+"\n");
                tbuttonActive.setSelected(false);
                return;
            }
            catch (NumberFormatException e) {
                Log("Invalid number (port, period, txttl or ackttl): "+e+"\n");
                tbuttonActive.setSelected(false);
                return;
            }
            
        } else {
            // Stop router
            stop_router();
        }
    }//GEN-LAST:event_tbuttonActiveActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        if (tbuttonActive.isSelected())
            stop_router();
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void editDataDelayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDataDelayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editDataDelayActionPerformed

    private void checkSlowDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSlowDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkSlowDataActionPerformed

    private void jCheckBoxMulticastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMulticastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMulticastActionPerformed


    /** Stops router */
    private void stop_router() {
        if (daemon != null) {
            daemon.stopRunning();
            daemon= null;
        }
        if (route != null) {
            route.stop();
            route= null;
        }
        if (ds != null) {
            neig.clear_BYE(ds, local_name());
            neig.refresh_table(tabelaViz);
            ds.close();
            ds= null;
        }
        if (tbuttonActive.isSelected()) {
            Log("Router "+local_name()+" stopped\n");
        }
        editName.setEditable(true);
        editPorto.setEditable(true);
        editIP.setEditable(true);
//        checkSndIfChanges.setEnabled(true);
        editPeriodo.setEditable(true);
        editMinInterval.setEditable(true);
//        jCheckBoxMulticast.setEnabled(true);
        editPortMulticast.setEditable(true);
        editIPMulticast.setEditable(true);
//        checkSlowData.setEnabled(true);
        editDataDelay.setEditable(true);
    }

    /** Get node name from form */
    public char local_name() {
        try {
            return editName.getText().charAt(0);
        }
        catch(Exception e) {
            Log("Local name error: "+e);
        }
        return '*';
    }
    
    /** Checks if it is a local name */
    public boolean is_local_name(char nm) {
        return (nm == local_name());
    }
    
    /** Thread that handles socket events */
    public class Daemon extends Thread {
        volatile boolean keepRunning= true;
        DatagramSocket ds;
        
        // Constructor
        Daemon(DatagramSocket ds) {
            this.ds= ds;
        }
        
        // Thread main function
        @Override
        public void run() {
            byte [] buf= new byte[8096];
            DatagramPacket dp= new DatagramPacket(buf, buf.length);
            try {
                while (keepRunning) {
                    try {
                        ds.receive(dp);
                        ByteArrayInputStream BAis= 
                            new ByteArrayInputStream(buf, 0, dp.getLength());
                        DataInputStream dis= new DataInputStream(BAis);
                        System.out.println("Received packet ("+dp.getLength()+
                            ") from " + dp.getAddress().getHostAddress() +
                            ":" +dp.getPort());
                        
                        synchronized (main_lock) {
                            process_packet(dp, dis);
                        }
                    }
                    catch (SocketException se) {
                        if (keepRunning)
                            Log("recv UDP SocketException : " + se + "\n");
                    }
                }
            }
            catch(IOException e) {
                if (keepRunning)
                    Log("IO exception receiving data from socket : " + e);
            }
        }
        
        // Stops thread
        public void stopRunning() {
            keepRunning= false;
        }
    }


    /** processes incoming packet */
    boolean process_packet(DatagramPacket dp, DataInputStream dis) {
        byte code;
        char sender;
        try {
            code= dis.readByte();     // read code
            sender= dis.readChar();   // read sender id
            String ip= dp.getAddress().getHostAddress();  // Get sender address            
            if (ip.startsWith("127.")) {
                try {
                    ip= InetAddress.getLocalHost().getHostAddress();
                }
                catch (UnknownHostException e) {
                    Log("Error converting address '127.*'\n");
                    return false;
                }
            }
            
            switch(code) {
                case PKT_HELLO:
                    Log("PKT_HELLO("+sender+")\n");
                    HELLO_rcv++;
                    // Update values
                    int dist= dis.readInt();
                    if (dis.available() != 0) {
                        Log("Packet too long\n");
                        return false;
                    }
                    if (tbuttonActive.isSelected()) {
                        boolean ok= neig.add_neig(sender, ip, dp.getPort(), 
                            dist, ds);
                        if (ok) {
                            neig.refresh_table(tabelaViz);
                            if (checkSndIfChanges.isSelected()) {
                                route.network_changed(true);
                            }
                        }
                    }
                    break;
                case PKT_BYE:
                    Log("PKT_BYE("+sender+")\n");
                    BYE_rcv++;
                    if (dis.available() != 0) {
                        Log("Packet too long\n");
                        return false;
                    }
                    if (tbuttonActive.isSelected()) {
                        boolean ok= neig.del_neig(sender, false, ds, 
                            local_name());
                        if (ok) {
                            neig.refresh_table(tabelaViz);
                            if (checkSndIfChanges.isSelected())
                                route.network_changed(true);                            
                        }
                    }
                    break;
                case PKT_ROUTE:
                    ROUTE_rcv++;
                    if (jCheckBoxMulticast.isSelected())
                        return true;
                    return route.process_ROUTE(sender, dp, ip, dis, false);
                case PKT_DATA:
                    DATA_rcv++;
                    return route.process_DATA(sender, dp, ip, dis);
                default:
                    Log("Invalid packet code ("+code+")\n");
                    INVALID_rcv++;
                    return false;
                }
            }
            catch(IOException e) {
                Log("Packet too short\n");
                return false;
            }
            return true;
    }

   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new router().setVisible(true);
    }
    
    /** Writes messages in window */
    public void Log(final java.lang.String s) {
        texto.append(s);
        System.out.print(s);
    }         

    /** Clear statistics */
    public void zero_statistics() {
        HELLO_snt= 0;
        HELLO_rcv= 0;
        BYE_snt= 0;
        BYE_rcv= 0;
        ROUTE_loc= 0;
        ROUTE_snt= 0;
        ROUTE_rcv= 0;
        DATA_snt= 0;
        DATA_rcv= 0;
        INVALID_rcv= 0;
        Dijkstra_cnt= 0;        
    }
    
    /** Writes statistics */
    public void write_statistics() {
        Log("****Statistics**********************************************\n"+
            "HELLO snt:"+HELLO_snt+" rcv:"+HELLO_rcv+
            "; BYE snt:"+BYE_snt+" rcv:"+BYE_rcv+
            "\nROUTE loc:"+ROUTE_loc+" snt:"+ROUTE_snt+" rcv:"+ROUTE_rcv+
            "\nDATA snt:"+DATA_snt+" rcv:"+DATA_rcv+
            "; Invalid rcv:"+INVALID_rcv+"; Dijkstra cnt:"+Dijkstra_cnt+"\n"+
            "************************************************************\n");
    }
    
    ////////////////////////////////////////////////////////////////////
    
    /** Synchronization lock */
    final public Integer main_lock= new Integer(0);
    
    /** Datagram socket */
    private DatagramSocket ds;
    /** Socket daemon */
    private Daemon daemon;
    /** meighbour list */
    private neighbourList neig;
    /** routing object */
    private routing route;
    
    /* Statistical counters */
    public int HELLO_snt;
    public int HELLO_rcv;
    public int BYE_snt;
    public int BYE_rcv;
    public int ROUTE_loc;   // only counts local routing
    public int ROUTE_snt;
    public int ROUTE_rcv;
    public int DATA_snt;
    public int DATA_rcv;
    public int INVALID_rcv;
    public int Dijkstra_cnt;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton buttonAdd;
    javax.swing.JButton buttonDist;
    javax.swing.JButton buttonEnviar;
    javax.swing.JButton buttonLimpar;
    javax.swing.JButton buttonRem;
    javax.swing.JCheckBox checkSlowData;
    javax.swing.JCheckBox checkSndIfChanges;
    javax.swing.JTextField editDataDelay;
    javax.swing.JTextField editIP;
    javax.swing.JTextField editIPMulticast;
    javax.swing.JTextField editMensagem;
    javax.swing.JTextField editMinInterval;
    javax.swing.JTextField editName;
    javax.swing.JTextField editNeigDist;
    javax.swing.JTextField editNeigIP;
    javax.swing.JTextField editNeigName;
    javax.swing.JTextField editNeigPorto;
    javax.swing.JTextField editNomeDest;
    javax.swing.JTextField editPeriodo;
    javax.swing.JTextField editPortMulticast;
    javax.swing.JTextField editPorto;
    javax.swing.JCheckBox jCheckBoxMulticast;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel10;
    javax.swing.JLabel jLabel11;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JLabel jLabel8;
    javax.swing.JLabel jLabel9;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanel3;
    javax.swing.JPanel jPanel4;
    javax.swing.JPanel jPanel5;
    javax.swing.JPanel jPanel6;
    javax.swing.JPanel jPanel7;
    javax.swing.JPanel jPanel8;
    javax.swing.JPanel jPanel9;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JScrollPane jScrollPane3;
    javax.swing.JTable tabelaRoute;
    javax.swing.JTable tabelaViz;
    javax.swing.JToggleButton tbuttonActive;
    javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
  
}
